// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnUt9xzODbCV-LgciSMUF3KgGvm2aT7Js',
    appId: '1:165821714909:web:6438bb8f871b15fbcfe634',
    messagingSenderId: '165821714909',
    projectId: 'onboard-72490',
    authDomain: 'onboard-72490.firebaseapp.com',
    storageBucket: 'onboard-72490.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5y08iguG1xaDNGkH6reuqGEWYi4pkpPg',
    appId: '1:165821714909:android:2511fe0a5c42e38fcfe634',
    messagingSenderId: '165821714909',
    projectId: 'onboard-72490',
    storageBucket: 'onboard-72490.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfSkXB9L2H_PmHS4yrJHUX8HwGqSVC5jE',
    appId: '1:165821714909:ios:ed5e121be09bc09fcfe634',
    messagingSenderId: '165821714909',
    projectId: 'onboard-72490',
    storageBucket: 'onboard-72490.appspot.com',
    iosClientId: '165821714909-4j1lmoal56ak0i6fpjmb576ib27qs8qg.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.crmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfSkXB9L2H_PmHS4yrJHUX8HwGqSVC5jE',
    appId: '1:165821714909:ios:ed5e121be09bc09fcfe634',
    messagingSenderId: '165821714909',
    projectId: 'onboard-72490',
    storageBucket: 'onboard-72490.appspot.com',
    iosClientId: '165821714909-4j1lmoal56ak0i6fpjmb576ib27qs8qg.apps.googleusercontent.com',
    iosBundleId: 'com.mycompany.crmapp',
  );
}
